name: Flaky detection

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Test 1
        run: ./gradlew :ignite-raft:test
        
      - name: Test 2
        run: ./gradlew :ignite-raft:test

      - name: Test 3
        run: ./gradlew :ignite-raft:test
        
      - name: Test 4
        run: ./gradlew :ignite-raft:test
        
      - name: Test 5
        run: ./gradlew :ignite-raft:test
        
      - name: Test 6
        run: ./gradlew :ignite-raft:test
        
      - name: Test 7
        run: ./gradlew :ignite-raft:test
        
      - name: Test 8
        run: ./gradlew :ignite-raft:test
        
      - name: Test 9
        run: ./gradlew :ignite-raft:test
        
      - name: Test 10
        run: ./gradlew :ignite-raft:test
